export const companyData = [
  {
    id: 1,
    name: "TechNova",
    logo: null, // Using placeholder
    status: "Active",
    description:
      "TechNova is a leading technology company specializing in AI-powered solutions for enterprise applications.",
    tags: ["Technology", "AI", "Enterprise Software"],
    foundedYear: 2015,
    employeeRange: "500-1000",
    valuation: "75M",
    headquarters: "San Francisco, CA",
    website: "https://technova-ai.com",
    contact: {
      email: "info@technova-ai.com",
      phone: "+1 (415) 555-7890",
      address: "123 Innovation Way, San Francisco, CA 94107",
    },
  },
  {
    id: 2,
    name: "GreenEnergy",
    logo: "https://placehold.co/100x100?text=GE",
    status: "Active",
    description:
      "Renewable energy solutions provider focusing on solar and wind power technologies.",
    tags: ["Energy", "Renewable", "Sustainability"],
    foundedYear: 2010,
    employeeRange: "100-500",
    valuation: "45M",
    headquarters: "Austin, TX",
    website: "https://greenenergy.com",
    contact: {
      email: "contact@greenenergy.com",
      phone: "+1 (512) 555-3421",
      address: "450 Green Tech Blvd, Austin, TX 78701",
    },
  },
  {
    id: 3,
    name: "HealthPlus",
    logo: "https://placehold.co/100x100?text=H+",
    status: "Inactive",
    description:
      "Healthcare technology platform providing telemedicine and patient management solutions.",
    tags: ["Healthcare", "Telemedicine", "SaaS"],
    foundedYear: 2018,
    employeeRange: "50-100",
    valuation: "30M",
    headquarters: "Boston, MA",
    website: "https://healthplus.io",
    contact: {
      email: "support@healthplus.io",
      phone: "+1 (617) 555-9876",
      address: "200 Medical Drive, Boston, MA 02115",
    },
  },
  {
    id: 4,
    name: "FinTrack",
    logo: null,
    status: "Active",
    description:
      "Financial analytics platform for investment professionals and institutions.",
    tags: ["Finance", "Analytics", "B2B"],
    foundedYear: 2016,
    employeeRange: "100-250",
    valuation: "60M",
    headquarters: "New York, NY",
    website: "https://fintrack.com",
    contact: {
      email: "info@fintrack.com",
      phone: "+1 (212) 555-1234",
      address: "350 Wall Street, New York, NY 10005",
    },
  },
  {
    id: 5,
    name: "EduSmart",
    logo: "https://placehold.co/100x100?text=ES",
    status: "Pending",
    description:
      "Online learning platform offering courses in technology, business, and creative fields.",
    tags: ["Education", "E-learning", "Tech"],
    foundedYear: 2019,
    employeeRange: "25-50",
    valuation: "15M",
    headquarters: "Seattle, WA",
    website: "https://edusmart.com",
    contact: {
      email: "hello@edusmart.com",
      phone: "+1 (206) 555-6789",
      address: "500 Learning Lane, Seattle, WA 98101",
    },
  },
  {
    id: 6,
    name: "LogiTech",
    logo: "https://placehold.co/100x100?text=LT",
    status: "Active",
    description:
      "Supply chain and logistics management software for global enterprises.",
    tags: ["Logistics", "Supply Chain", "SaaS"],
    foundedYear: 2014,
    employeeRange: "250-500",
    valuation: "90M",
    headquarters: "Chicago, IL",
    website: "https://logitech-solutions.com",
    contact: {
      email: "sales@logitech-solutions.com",
      phone: "+1 (312) 555-4321",
      address: "800 Supply Chain Blvd, Chicago, IL 60607",
    },
  },
];
